/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: {
          0: "#0a0a0c",
          1: "#111114",
          2: "#18181c",
          3: "#222228",
          4: "#2a2a32",
          5: "#363640",
        },
        accent: {
          DEFAULT: "#6366f1",
          hover: "#818cf8",
          muted: "#4f46e5",
          subtle: "rgba(99,102,241,0.12)",
        },
        grade: {
          a: "#22c55e",
          'a-bg': "rgba(34,197,94,0.12)",
          b: "#84cc16",
          'b-bg': "rgba(132,204,22,0.12)",
          c: "#f59e0b",
          'c-bg': "rgba(245,158,11,0.12)",
          d: "#f97316",
          'd-bg': "rgba(249,115,22,0.12)",
          f: "#ef4444",
          'f-bg': "rgba(239,68,68,0.12)",
        },
        text: {
          primary: "#e4e4e7",
          secondary: "#a1a1aa",
          muted: "#71717a",
          disabled: "#52525b",
        },
        semantic: {
          success: "#22c55e",
          'success-bg': "rgba(34,197,94,0.12)",
          warning: "#f59e0b",
          'warning-bg': "rgba(245,158,11,0.12)",
          error: "#ef4444",
          'error-bg': "rgba(239,68,68,0.12)",
          info: "#6366f1",
          'info-bg': "rgba(99,102,241,0.12)",
        },
      },
      fontFamily: {
        sans: [
          "Inter",
          "General Sans",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        display: [
          "General Sans",
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      fontSize: {
        'eyebrow': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '500' }],
        'caption': ['11px', { lineHeight: '16px' }],
        'body-sm': ['13px', { lineHeight: '20px' }],
        'body': ['14px', { lineHeight: '22px' }],
        'lead': ['16px', { lineHeight: '24px' }],
        'display-sm': ['clamp(1.2rem, 3vw, 1.5rem)', { lineHeight: '1.2', fontWeight: '700' }],
        'display': ['clamp(1.5rem, 5vw, 3rem)', { lineHeight: '1.1', fontWeight: '700' }],
        'display-lg': ['clamp(2rem, 8vw, 4.5rem)', { lineHeight: '1', fontWeight: '800' }],
      },
      borderRadius: {
        'card': '8px',
        'pill': '9999px',
      },
      boxShadow: {
        'card': '0 1px 2px rgba(0,0,0,0.3), 0 1px 4px rgba(0,0,0,0.15)',
        'card-hover': '0 2px 8px rgba(0,0,0,0.35), 0 1px 3px rgba(0,0,0,0.2)',
        'modal': '0 8px 32px rgba(0,0,0,0.5), 0 2px 8px rgba(0,0,0,0.3)',
        'dropdown': '0 4px 16px rgba(0,0,0,0.4), 0 1px 3px rgba(0,0,0,0.2)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s cubic-bezier(0.32, 0.72, 0, 1)',
        'slide-up': 'slideUp 0.35s cubic-bezier(0.32, 0.72, 0, 1)',
        'scale-in': 'scaleIn 0.25s cubic-bezier(0.32, 0.72, 0, 1)',
        'spring-up': 'springUp 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'shimmer': 'shimmer 2s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 3s ease-in-out infinite',
        'breathe': 'breathe 4s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
        'progress-pulse': 'progressPulse 2s ease-in-out infinite',
        'radar-sweep': 'radarSweep 3s ease-in-out infinite',
        'card-enter': 'cardEnter 0.4s cubic-bezier(0.32, 0.72, 0, 1)',
        'hover-lift': 'hoverLift 0.2s cubic-bezier(0.32, 0.72, 0, 1) forwards',
        'magnetic-press': 'magneticPress 0.15s cubic-bezier(0.32, 0.72, 0, 1)',
        'confetti-fall': 'confettiFall 2.5s ease-in forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        springUp: {
          '0%': { opacity: '0', transform: 'translateY(12px) scale(0.97)' },
          '60%': { opacity: '1', transform: 'translateY(-2px) scale(1.01)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.6' },
          '50%': { transform: 'scale(1.05)', opacity: '1' },
        },
        progressPulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        radarSweep: {
          '0%': { transform: 'rotate(0deg) translateX(6px)', opacity: '0.3' },
          '50%': { transform: 'rotate(180deg) translateX(6px)', opacity: '1' },
          '100%': { transform: 'rotate(360deg) translateX(6px)', opacity: '0.3' },
        },
        cardEnter: {
          '0%': { opacity: '0', transform: 'translateY(12px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        hoverLift: {
          '0%': { transform: 'translateY(0) scale(1)' },
          '100%': { transform: 'translateY(-4px) scale(1.01)' },
        },
        confettiFall: {
          '0%': { transform: 'translateY(0) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(100vh) rotate(720deg)', opacity: '0' },
        },
        magneticPress: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(0.97)' },
          '100%': { transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
};
